#! /usr/bin/env zsh

zmodload zsh/mapfile  # http://stackoverflow.com/a/12652267/2954547

random_255() {
    [[ -z $1 ]] && return 1

    head -c $(( $1 )) /dev/random |\
        xxd -p |\
        fold -w2 |\
        xargs -n1 -I_ printf "%i\n" 0x_
}


generate_passphrase() {
    n="${1:-3}"
    dictfile="${2:-/usr/share/dict/words}"

    dict=( "${(f)mapfile[$dictfile]}" )
    dict_size=$#dict

    passphrase=()
    while read -r i; do
        passphrase+="${dict[$(( $i * $dict_size / 255 ))]}"
    done < <( random_255 $n )

    echo ${${passphrase:gs/ /_}:l}
}

main() {
    if [[ $( printf "%i\n" "$1" ) != "$1" || "$1" < 1 ]]; then
        print -u2 "Invalid number of words: '$1'"
        exit 1
    fi
    generate_passphrase $1 =( cat /usr/share/dict/words /usr/share/dict/web2a /usr/share/dict/propernames )
}

main "$@"
